# Generated by Django 5.1.7 on 2025-04-01 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routineModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('period', models.IntegerField(blank=True, help_text='例：7 = 毎週、30 = 毎月', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='周期')),
                ('create_at', models.TimeField(auto_now_add=True, verbose_name='作成日時')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('notice_text', models.TextField(max_length=400, verbose_name='通知内容')),
            ],
        ),
    ]
