# Generated by Django 5.1.8 on 2025-04-05 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinemodel',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='開始日時'),
        ),
    ]
